overrides: "git://github.com/pyexcel/pyexcel-mobans!/mobanfile.yaml"
configuration:
  configuration: pyexcel-xlsx.yml
targets:
  - Pipfile: Pipfile.jj2
  - README.rst: custom_README.rst.jj2
  - setup.py: setup.py
  - "docs/source/conf.py": "docs/source/conf.py.jj2"
  - .travis.yml: custom_travis.yml.jj2
  - MANIFEST.in: MANIFEST.in.jj2
  - .gitignore: gitignore.jj2
  - "tests/requirements.txt": "tests/requirements.txt"
